build-image:
	bash ./metabase_container/build-image.sh

create-container: build-image
	bash ./metabase_container/create-container.sh

start-container:
	bash ./metabase_container/start-container.sh

stop-container:
	bash ./metabase_container/stop-container.sh

clean-environment:
	bash ./metabase_container/clean.sh
